name: Blog Trip
favicon: null
layout_spectrum: 0.5399758543353528
typography_spectrum: 0.5337165286764503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8797166170552373
  lightness: 0.40766872046515346
  saturation: 0.24019697261974216
  rhythmicContrast: 0.7125862124375999
purpose: []
